#! /usr/bin/env python

from cosmoslik.waf.utils import build_f2py, opt_f2py, config_f2py

def options(opt):
    opt_f2py(opt)

def configure(conf):
    config_f2py(conf)
    
def build(bld):
    build_f2py(bld,
               source='temp_like.f90',
               module_name='pycamspec',
               extra_sources=[],
               includes=bld.path.find_node('pycamspec.so'),
               use='')
